In [1]:
import numpy as np
#Cargamos los paquetes que vamos a utilizar para esta base de datos.

In [30]:
data = np.genfromtxt("data/data.csv", delimiter=";",usecols=2,skip_header=1, dtype=str)
data=[i.replace(".","") for i in data]
#Para que en el caso de palma que son numeros mas grandes y que se leian como 3 y no como 3345 he tenido que ponerlo primero como strings
data=np.asarray(data)
data=data.astype(int)
#en este punto lo incorporo de nuevo a numeros para poder ptrocesar los datos.
print(data)
#Descargamos los datos de la tabla, pero solo descargamos los numeros, que son los que nos interesa.

[  70    0   27   64    6   47    0   16   39    8  178    2   43  108
   70   58    1   18   52    6  109    1   40  103    6    6    0    2
    7   -1   57    0   12   65   -8    3    0    3    2    1   62    1
   26   59    3   10    0    4   10    0   50    0   15   55   -5  340
    4  112  294   46   20    0    9   30  -10  100    0   37   85   15
  109    1   29   94   15   41    0   14   42   -1  208    0   92  219
  -11   35    0   17   25   10   14    0   11    8    6    5    0    1
    4    1  434    1   98  315  119    3    0    0    0    3   35    0
   14   45  -10    1    0    0    3   -2  186    1   42  172   14   39
    0   13   30    9   91    1   28   52   39    4    0    1    3    1
  334    0   71  246   88   16    0    2   12    4   58    0   17   44
   14   24    0   10   23    1  277    3   98  218   59  445    0   81
  341  104   13    0    8   10    3  239    1   88  189   50   19    0
    9   30  -11  264    2   95  200   64   33    0   14   29    4    6
    0 

In [31]:
valors = data.reshape(67,5)
valors
#en este caso he tenido que acudir al documento orginal para ver como estaba organizado y hay 67 filas y 5 columnas asi que he constituido la matriz para que los datos estuviesen en orden, para que nos de los datos correctos.

array([[  70,    0,   27,   64,    6],
       [  47,    0,   16,   39,    8],
       [ 178,    2,   43,  108,   70],
       [  58,    1,   18,   52,    6],
       [ 109,    1,   40,  103,    6],
       [   6,    0,    2,    7,   -1],
       [  57,    0,   12,   65,   -8],
       [   3,    0,    3,    2,    1],
       [  62,    1,   26,   59,    3],
       [  10,    0,    4,   10,    0],
       [  50,    0,   15,   55,   -5],
       [ 340,    4,  112,  294,   46],
       [  20,    0,    9,   30,  -10],
       [ 100,    0,   37,   85,   15],
       [ 109,    1,   29,   94,   15],
       [  41,    0,   14,   42,   -1],
       [ 208,    0,   92,  219,  -11],
       [  35,    0,   17,   25,   10],
       [  14,    0,   11,    8,    6],
       [   5,    0,    1,    4,    1],
       [ 434,    1,   98,  315,  119],
       [   3,    0,    0,    0,    3],
       [  35,    0,   14,   45,  -10],
       [   1,    0,    0,    3,   -2],
       [ 186,    1,   42,  172,   14],
       [  39,    0,   13,

In [ ]:
#Los resultado que nos van a dar es de todas las columnas una por una y seguidas de una coma, de esta manera veremos que resultado nos y asi poderlo computar en un futuro segun el dato que nos interese de una manera conjunta.

In [32]:
sumatot= np.sum(valors,axis=0)
sumatot

array([9455,   40, 2960, 8559,  896])

In [33]:
mediatot=np.mean(valors,axis=0)
mediatot

array([141.11940299,   0.59701493,  44.17910448, 127.74626866,
        13.37313433])

In [34]:
varianzatot=np.std(valors,axis=0)
varianzatot

array([408.24888233,   2.04472165, 135.04061582, 405.29334662,
        32.63174712])